<?xml version="1.0" standalone="yes"?>
<DATAPACKET Version="2.0">
<METADATA>
<FIELDS>
<FIELD attrname="CVE_CLPV" fieldtype="string" WIDTH="10"/>
<FIELD attrname="NUM_ALMA" fieldtype="i4"/>
<FIELD attrname="CVE_PEDI" fieldtype="string" WIDTH="20"/>
<FIELD attrname="ESQUEMA" fieldtype="i4"/>
<FIELD attrname="DES_TOT" fieldtype="r8"/>
<FIELD attrname="DES_FIN" fieldtype="r8"/>
<FIELD attrname="CVE_VEND" fieldtype="string" WIDTH="5"/>
<FIELD attrname="COM_TOT" fieldtype="r8"/>
<FIELD attrname="NUM_MONED" fieldtype="i4"/>
<FIELD attrname="TIPCAMB" fieldtype="r8"/>
<FIELD attrname="STR_OBS" fieldtype="string" WIDTH="255"/>
<FIELD attrname="ENTREGA" fieldtype="string" WIDTH="25"/>
<FIELD attrname="SU_REFER" fieldtype="string" WIDTH="20"/>
<FIELD attrname="TOT_IND" fieldtype="r8"/>
<FIELD attrname="MODULO" fieldtype="string" WIDTH="4"/>
<FIELD attrname="CONDICION" fieldtype="string" WIDTH="25"/>
<FIELD attrname="dtfield" fieldtype="nested"><FIELDS>
<FIELD attrname="CANT" fieldtype="r8"/>
<FIELD attrname="CVE_ART" fieldtype="string" WIDTH="20"/>
<FIELD attrname="DESC1" fieldtype="r8"/>
<FIELD attrname="DESC2" fieldtype="r8"/>
<FIELD attrname="DESC3" fieldtype="r8"/>
<FIELD attrname="IMPU1" fieldtype="r8"/>
<FIELD attrname="IMPU2" fieldtype="r8"/>
<FIELD attrname="IMPU3" fieldtype="r8"/>
<FIELD attrname="IMPU4" fieldtype="r8"/>
<FIELD attrname="COMI" fieldtype="r8"/>
<FIELD attrname="PREC" fieldtype="r8"/>
<FIELD attrname="NUM_ALM" fieldtype="i4"/>
<FIELD attrname="STR_OBS" fieldtype="string" WIDTH="255"/>
<FIELD attrname="REG_GPOPROD" fieldtype="i4"/>
<FIELD attrname="REG_KITPROD" fieldtype="i4"/>
<FIELD attrname="NUM_REG" fieldtype="i4"/>
<FIELD attrname="COSTO" fieldtype="r8"/>
<FIELD attrname="TIPO_PROD" fieldtype="string" WIDTH="1"/>
<FIELD attrname="TIPO_ELEM" fieldtype="string" WIDTH="1"/>
<FIELD attrname="MINDIRECTO" fieldtype="r8"/>
<FIELD attrname="TIP_CAM" fieldtype="r8"/>
<FIELD attrname="FACT_CONV" fieldtype="r8"/>
<FIELD attrname="UNI_VENTA" fieldtype="string" WIDTH="10"/>
<FIELD attrname="IMP1APLA" fieldtype="i4"/>
<FIELD attrname="IMP2APLA" fieldtype="i4"/>
<FIELD attrname="IMP3APLA" fieldtype="i4"/>
<FIELD attrname="IMP4APLA" fieldtype="i4"/>
<FIELD attrname="PREC_SINREDO" fieldtype="r8"/>
<FIELD attrname="COST_SINREDO" fieldtype="r8"/>
<FIELD attrname="LOTE" fieldtype="string" WIDTH="16"/>
<FIELD attrname="PEDIMENTO" fieldtype="string" WIDTH="16"/>
<FIELD attrname="FECHCADUC" fieldtype="dateTime"/>
<FIELD attrname="FECHADUANA" fieldtype="dateTime"/>
</FIELDS>
<PARAMS/></FIELD></FIELDS><PARAMS/>
</METADATA>
<ROWDATA><ROW CVE_CLPV="         4" NUM_ALMA="1" CVE_PEDI="" ESQUEMA="1" DES_TOT="0" DES_FIN="0" CVE_VEND="" COM_TOT="0" NUM_MONED="1" TIPCAMB="1" STR_OBS="SORIANA" MODULO="FACT" CONDICION="SORIANA"><dtfield>
<ROWdtfield CANT="16" CVE_ART="7502257600086" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="16" CVE_ART="7502257600093" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="19" CVE_ART="7502257600109" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="8" CVE_ART="7502257600116" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="4" CVE_ART="7502257600154" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="10" CVE_ART="7502257600178" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="6" CVE_ART="7502257600222" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="10" CVE_ART="7502257600239" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="5" CVE_ART="7502257600277" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="3" CVE_ART="7502257600291" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
<ROWdtfield CANT="14" CVE_ART="7502257601137" DESC1="0" DESC2="0" DESC3="0" IMPU1="0" IMPU2="0" IMPU3="0" IMPU4="" COMI="0" PREC="" NUM_ALM="1" STR_OBS="" REG_GPOPROD="0" COSTO="0" TIPO_PROD="P" TIPO_ELEM="N" TIP_CAM="1" UNI_VENTA="pz" IMP1APLA="6" IMP2APLA="6" IMP3APLA="6" IMP4APLA="0" PREC_SINREDO="" COST_SINREDO="0" />
</dtfield></ROW></ROWDATA></DATAPACKET>